version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: personal_finance_db
    ports:
      - "3306:3306"
    networks:
      - webapp-network

  web:
    build: ./income-service
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://root:password@db/personal_finance_db
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge
