version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: personal_finance_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webapp-network

  income-service:
    build: ./income-service
    command: flask run --host=0.0.0.0 --port=5001
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://root:password@db/personal_finance_db
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - webapp-network

  expense-service:
    build: ./expense-service
    command: flask run --host=0.0.0.0 --port=5002
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://root:password@db/personal_finance_db
    ports:
      - "5002:5002"
    depends_on:
      - db
    networks:
      - webapp-network

  frontend-service:
    build: ./frontend-service
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://root:password@db/personal_finance_db
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:password@db/personal_finance_db
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge

volumes:
  db_data:
